backend:
  name: github
  repo: martinriviere/wedding

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  # - label: "Pages"
  #   name: "pages"
  #   files:
  #     - label: "Accueil"
  #       name: "main"
  #       file: "content/main.md"
  #       fields:
  #         - { label: "Title", name: "title", widget: "string" }
  #         - { label: "Text", name: "body", widget: "markdown" }
  - label: "VIP"
    name: "team"
    folder: "content/vips"
    create: true
    identifier_field: name
    fields:
      - { label: "Nom", name: "name", widget: "string" }
      - { label: "Fonction", name: "function", widget: "string" }
      - {
          label: "Relation (fr√®re/soeur...)",
          name: "relation",
          widget: "string",
          required: false,
        }
      - { label: "Photo", name: "picture", widget: "image" }
  - label: "Activity"
    name: "activities"
    folder: "content/activities"
    create: true
    identifier_field: name
    fields:
      - { label: "Nom", name: "name", widget: "string" }
      - { label: "Texte", name: "body", widget: "markdown" }
      - { label: "Image", name: "picture", widget: "image" }
